// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DenemeTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void deneme() throws InterruptedException {
        driver.get("https://www.e-bebek.com/");
        driver.manage().window().maximize();
        driver.findElement(By.id("txtSearchBox")).click();
        Thread.sleep(2000);
        driver.findElement(By.id("txtSearchBox")).sendKeys("kaşık maması");
        Thread.sleep(2000);
        driver.findElement(By.id("txtSearchBox")).sendKeys(Keys.ENTER);
        Thread.sleep(2000);
        boolean isContinue = true;
        int scroll = 1500;
        while (isContinue) {
            try {
                if (driver.findElement(By.cssSelector(".btn-buttonload")) != null) {
                    System.out.println("YAKALANDIN");
                    break;
                }
            } catch (Exception e) {
                js.executeScript("window.scrollTo(0," + scroll + ")");
                Thread.sleep(2000);
                scroll += 1000;
                System.out.println("SIKINTI YOK");
                System.out.println("---------------------------");
            }
        }
        js.executeScript("window.scrollTo(0," + scroll + ")");


        Thread.sleep(5000);

        By mySelector = By.xpath("//button[.=\"Sepete Ekle\"]");
        List<WebElement> myElements = driver.findElements(mySelector);
        int i = 0;
        for (WebElement e : myElements) {
            System.out.println(i++);
        }

        System.out.println(i);
//      driver.findElement(By.xpath("(//button[@id='addToCartBtn'])[43]")).click();
        Thread.sleep(5000);
//        driver.findElement(By.cssSelector(".col-6:nth-child(43) .product-item-anchor .product-item-content")).click();
        driver.findElement(By.xpath("/html/body/app-root/cx-storefront/main/cx-page-layout/cx-page-slot[3]/eb-product-list/div/section/div/div/div/div[2]/eb-product-scroll/div/div/eb-product-list-item[43]/div/eb-generic-link/a/div/div[2]/span")).click();
        System.out.println("as");
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(5000L));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("addToCartBtn")));
        }
        Thread.sleep(5000);
        driver.findElement(By.id("addToCartBtn")).click();
        Thread.sleep(50000);

    }
}
