// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EbebekQAFinalCase {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void deneme() throws InterruptedException {
        //Ebebek sitesine giriş
        driver.get("https://www.e-bebek.com/");
        //Tarayıcıyı tam ekran yapma
        driver.manage().window().maximize();
        //Arama kutusuna tıklama
        driver.findElement(By.id("txtSearchBox")).click();
        //kutu açılana kadar bekleme
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(5000L));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".header__menu-search-content-buttons")));
        }
        //kutuya "kaşık maması" yazma
        driver.findElement(By.id("txtSearchBox")).sendKeys("kaşık maması");
        //ENTER basma
        driver.findElement(By.id("txtSearchBox")).sendKeys(Keys.ENTER);
        //Sayfa yüklenene kadar bekleme
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(5000L));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("body > app-root > cx-storefront > main > cx-page-layout > cx-page-slot.SearchResultsListSlot.has-components.ng-star-inserted > eb-product-list > div > section > div > div > div > div.cx-product-container.row.ng-star-inserted > div > p")));
        }

        int scroll = 1500;
        //Sayfada "Tükendi" butonu görene kadar sayfayı aşağı kaydırma
        while (true) {
            try {
                if (driver.findElement(By.cssSelector(".btn-buttonload")) != null) {
                    break;
                }
            } catch (Exception e) {
                js.executeScript("window.scrollTo(0," + scroll + ")");
                Thread.sleep(2000);
                scroll += 1000;
            }
        }
        //Sepete ekle butonlarını bulma ve bir List içine atma
        By mySelector = By.xpath("//button[.=\"Sepete Ekle\"]");
        List<WebElement> myElements = driver.findElements(mySelector);
        //List'in boyutunu alma
        int i = myElements.size();
        //İmleci son ürünün üzerine götürme
        WebElement element = driver.findElement(By.cssSelector(".col-6:nth-child(" + i + ") .product-item-anchor .product-item-content"));
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);
        Thread.sleep(1000);
        //Son ürüne tıklama
        driver.findElement(By.cssSelector(".col-6:nth-child(" + i + ") .product-item-anchor .product-item-content")).click();
        //Açılan sayfada Sepete ekle butonu görünene kadar bekleme
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(5000L));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".ng-star-inserted:nth-child(4) > .ng-untouched > #addToCartBtn")));
        }
        //Sepete ekle butonuna tıklama
        driver.findElement(By.id("addToCartBtn")).click();
        //Sepeti gör butonuna kadar bekleme
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(5000L));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#btnShowCart")));
        }
        Thread.sleep(500);
        //Sepeti gör butonuna tıklama
        driver.findElement(By.cssSelector("#btnShowCart")).click();
        //Alışverişi Tamamla butonunu görene kadar bekleme
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(5000L));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#btnGoToShippingAddress > .ng-star-inserted")));
        }
        //Alışverişi tamamla butonuna tıklama
        driver.findElement(By.cssSelector("#btnGoToShippingAddress > .ng-star-inserted")).click();

        Thread.sleep(5000);

    }
}
